# Generated by Django 2.2.12 on 2021-01-23 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlistings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlistings',
            name='price',
        ),
    ]
