# Generated by Django 2.2.12 on 2021-01-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210127_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='watchers',
        ),
        migrations.AlterField(
            model_name='listing',
            name='currentBid',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='startingBid',
            field=models.FloatField(default=0),
        ),
    ]
