# Generated by Django 2.2.12 on 2021-02-09 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210130_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='auctions/static/auctions/img'),
        ),
    ]
