# Generated by Django 2.2.12 on 2021-01-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='auctionlistings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=512)),
                ('image', models.CharField(max_length=5000)),
                ('bid', models.IntegerField()),
            ],
        ),
    ]
